Dashboard |
Soundbendor/smart-bin-app pull request #109
Opened 2024-02-21 23:50 UTC by stalberm

## Description

* Did something

2024-02-22 17:43 UTC, theusaf requested changes
Don't forget to add documentation for your widgets!

2024-02-22 17:43 UTC, theusaf commented on lib/pages/detection/detection.dart
> +      onTap: () => GoRouter.of(context).go('/main/detections'),
The reason I had this as `.pop()` was to preserve scrolling and other state information in the detection list when the user goes back.
Can this be reverted?

2024-02-22 17:43 UTC, theusaf commented on lib/widgets/image.dart
> +        // key: key,
```suggestion
```

2024-02-28 23:22 UTC, bpugh5 commented on lib/main.dart
> +  ], child: BinsightAiApp(skipSetUp: devices.isNotEmpty)));
This needs to be reverted still I think

2024-02-28 23:34 UTC, theusaf submitted a review, later dismissed

2024-03-02 00:20 UTC, bpugh5 commented on lib/widgets/circular_chart.dart
> +        palette: const [
Did we ever determine what happens if there's more fields than there are colors in the palette? What would we do in that situation?

2024-03-05 19:43 UTC, stalberm commented on lib/widgets/circular_chart.dart
> +        palette: const [
Not worried about it right now. We can worry about it once we figure out our category situation thing because at that point we can just have as many colors as there are categories.

2024-03-05 19:44 UTC, merged