Help Page & Support | Finish implementation of Help Page and Contact Support Email functionality
Soundbendor/smart-bin-app pull request #112
Opened 2024-02-27 01:49 UTC by kimberlymarkley

## Description
* add email button and disappear the horizontal borders after dropdown effect
* add permissions to AndroidManifest for urlLauncher
* add permissions to iOS Info.plist for urlLauncher
* fix gradle build issue, specify compileSKDversion 34 and debug AndroidManifest schemelisting
* extract launch email logic into function, add try/catch error reporting
* bug squash: removed Expanded widgets from inside ExpansionTiles
* extract ExpansionTiles in list into widgets
* remove 'My Bin' from drawer widget, since it is unneeded

## Related Issues
* Resolves #67
* Resolves #11 

## Screenhots

<img width="497" alt="Screenshot 2024-02-26 at 5 45 40 PM" src="https://github.com/Soundbendor/smart-bin-app/assets/73560521/cab0e784-8f7b-43fc-8026-ff73ca04f4ed">
<img width="469" alt="Screenshot 2024-02-26 at 12 21 15 PM" src="https://github.com/Soundbendor/smart-bin-app/assets/73560521/1048c59d-8cc5-4afb-be4e-3d841d353628">
<img width="466" alt="Screenshot 2024-02-26 at 12 35 34 PM" src="https://github.com/Soundbendor/smart-bin-app/assets/73560521/2057df3b-a464-4695-827f-7d79e97a8464">

2024-02-28 23:16 UTC, theusaf requested changes

2024-02-28 23:16 UTC, theusaf commented on lib/pages/main/help.dart
> +                    ],
Rather than these hardcoded colors, maybe we should use theme colors.
```dart
Theme.of(context).colorScheme.primary
Theme.of(context).colorScheme.onPrimary
```

2024-02-28 23:17 UTC, bpugh5 commented on lib/pages/main/help.dart
> +                              color: Color.fromARGB(255, 255, 255, 255),
If this is just white, I think you should be able to use Colors.white!

2024-02-28 23:19 UTC, bpugh5 approved these changes
Looks good!! Awesome stuff.

2024-02-29 00:52 UTC, theusaf approved these changes

2024-02-29 18:09 UTC, stalberm approved these changes

2024-03-01 23:15 UTC, theusaf approved these changes

2024-03-01 23:16 UTC, merged