Annotation | State Abstraction
Soundbendor/smart-bin-app pull request #131
Opened 2024-03-09 22:02 UTC by stalberm

## Description
* Extracts the state related to annotating an image into a Provider
* Creates a new page for adding a label to the current annotation
* Provides drawing persistence for most recent annotation

2024-03-09 23:08 UTC, kimberlymarkley commented on lib/pages/detection/annotation.dart
> +import 'package:provider/provider.dart';
this can be moved up to right underneath other packages (i.e. under go_router)

2024-03-09 23:09 UTC, kimberlymarkley commented on lib/pages/detection/annotation.dart
> +import 'package:binsight_ai/util/providers.dart';
this can be moved down to the rest of the binsight package imports, in alphabetical order

2024-03-09 23:15 UTC, kimberlymarkley commented on lib/pages/detection/detection.dart
> +import 'package:provider/provider.dart';
same as above :)

2024-03-09 23:16 UTC, kimberlymarkley commented on lib/util/providers.dart
> +/// Notifiers listeners of changes to the annotation state
does it matter that some of these have a space between the '///' and some do not?

2024-03-09 23:18 UTC, kimberlymarkley commented on lib/widgets/free_draw.dart
> +            //When first touching within the image, create a single Offset
These comments are great!

2024-03-09 23:19 UTC, kimberlymarkley commented on lib/pages/detection/annotation.dart
>                              imageLink: snapshot.data as String,
is this where the imageLink is being generated?

2024-03-09 23:22 UTC, kimberlymarkley commented on lib/pages/detection/annotation.dart
> +  late final Future<String> imageLink;
did I correctly identify where this imageLinks is being generated? (see comment below)

2024-03-09 23:24 UTC, kimberlymarkley reviewed
This is so rad! Love seeing the state come into play. If you take a bit to organize the package imports and use a space after /// and //, that'd increase organization and readability.

2024-03-09 23:54 UTC, theusaf commented on lib/pages/detection/annotation.dart
>                              imageLink: snapshot.data as String,
The image link is being generated in the constructor of `AnnotationPage`. The image link is being used in this location.

2024-03-09 23:58 UTC, theusaf requested changes

2024-03-09 23:58 UTC, theusaf commented on lib/pages/detection/annotation.dart
> +                      message = "Please Enter A Label For Current Annotation";
The capitalization should be improved/decided
```suggestion
                      message = "Please Enter a Label for Current Annotation";
```

2024-03-09 23:58 UTC, theusaf commented on lib/util/providers.dart
> +/// Notifiers listeners of changes to the annotation state
I think it would be cleaner with a space between comment lines. Class looks good though!

2024-03-12 18:20 UTC, theusaf approved these changes

2024-03-12 18:30 UTC, kimberlymarkley approved these changes

2024-03-12 18:30 UTC, merged