Annotation | Label Search
Soundbendor/smart-bin-app pull request #152
Opened 2024-04-04 20:11 UTC by stalberm

## Description
* Replaces the old popup that prompted manually typing a label with a label search
* Adds json to contain all possible labels, search options are populated using this json
* Adds option to add label if it's not found in the provided list

2024-04-08 17:34 UTC, bpugh5 commented on lib/pages/detection/annotation.dart
> +import 'package:multiple_search_selection/multiple_search_selection.dart';
little itty bitty thing, could you slide into the imports in alphabetical order?

2024-04-08 17:36 UTC, bpugh5 commented on lib/pages/detection/annotation.dart
> +                              labels.isNotEmpty
could you comment this logic briefly just to describe what it does onPressed?

2024-04-08 17:40 UTC, bpugh5 reviewed
See comments! Nothing bad, but little things I noticed, otherwise looks good :)

2024-04-08 17:43 UTC, kimberlymarkley commented on .vscode/launch.json
> +{
I poked around online to see what this file is for, but couldn't figure out why we need it. Is it for versioning? or???

2024-04-08 17:48 UTC, kimberlymarkley approved these changes

2024-04-08 17:48 UTC, kimberlymarkley commented on lib/pages/detection/annotation.dart
> +
This code is super easy to read. Who says CS folks can't name stuff thoughtfully?!  :D

2024-04-08 18:50 UTC, stalberm commented on .vscode/launch.json
> +{
I really am not sure. I don't know when that got added sadly.

2024-04-10 05:58 UTC, theusaf commented on .vscode/launch.json
> +{
Might be worth removing and/or adding to gitignore. This file is generally for developer-specific configurations

2024-04-10 06:01 UTC, theusaf requested changes

2024-04-10 06:01 UTC, theusaf commented on lib/pages/detection/annotation.dart
> +  Future<void> readJson() async {
I think a better name could be `loadLabels` or something

2024-04-10 06:01 UTC, theusaf commented on lib/util/providers.dart
> +import 'package:binsight_ai/widgets/free_draw.dart';
Should probably be placed in its original location

2024-04-10 06:01 UTC, theusaf commented on lib/widgets/free_draw.dart
> -// Package imports:
To be consistent with other files, we should leave this in

2024-04-10 20:27 UTC, kimberlymarkley submitted a review, later dismissed

2024-04-11 02:43 UTC, bpugh5 approved these changes
Looks great!!

2024-04-11 21:17 UTC, theusaf commented on lib/widgets/free_draw.dart
> +// Package imports:
```suggestion

// Package imports:
import 'package:provider/provider.dart';
```

2024-04-11 21:18 UTC, theusaf approved these changes

2024-04-11 21:19 UTC, merged