Retreieve version number dynamically
Soundbendor/smart-bin-app pull request #174
Opened 2024-05-01 18:00 UTC by theusaf

## Description

* Uses the app's version number in the help screen rather than a hardcoded value

2024-05-02 00:56 UTC, kimberlymarkley commented on lib/widgets/top_nav_bar.dart
>              // TODO: create a version number that is updated automatically
Sweet! We can delete this TODO :)

2024-05-02 01:08 UTC, kimberlymarkley requested changes
Can we delete that TODO? Thank you, Daniel

2024-05-03 17:40 UTC, kimberlymarkley approved these changes

2024-05-06 17:48 UTC, stalberm approved these changes

2024-05-06 17:54 UTC, merged