Cloud | API Call Update
Soundbendor/smart-bin-app pull request #207
Opened 2024-05-21 23:12 UTC by stalberm

## Description
* Update API call in FetchImageData to use the new request body field "after_time" in order to retrieve images truly after the latest

2024-05-21 23:17 UTC, theusaf requested changes

2024-05-21 23:17 UTC, theusaf commented on lib/main.dart
> +        initialLocation: !widget.skipSetUp ? '/main' : '/set-up',
```suggestion
        initialLocation: widget.skipSetUp ? '/main' : '/set-up',
```

2024-05-22 00:23 UTC, kimberlymarkley submitted a review, later dismissed

2024-05-22 04:10 UTC, theusaf approved these changes

2024-05-22 04:22 UTC, kimberlymarkley approved these changes

2024-05-22 04:45 UTC, merged