Help Page | Implement Navigation Shell & Routing
Soundbendor/smart-bin-app pull request #71
Opened 2024-01-25 06:32 UTC by kimberlymarkley

## Description
* extract BottomNavBarWidget into seperate file for code modularity
* create drawer style TopNavBar
* rename BottomNavBar and incorporate TopNavBar into NavigationShell logic
* connect the new Help Page stub to new TopNavBar Drawer and Routes
* tidy imports & fix formatting

## Related Issues
* References #11 
* References #67 

## Screenhots

<img width="493" alt="Screenshot 2024-01-24 at 9 13 06 PM" src="https://github.com/Soundbendor/smart-bin-app/assets/73560521/fa39153f-e08a-4909-ad8a-9ddd0cd6ce9a">
<img width="489" alt="Screenshot 2024-01-24 at 9 35 03 PM" src="https://github.com/Soundbendor/smart-bin-app/assets/73560521/c6699f58-7c27-47f7-a68c-ff99eeab86e5">

2024-01-25 07:03 UTC, theusaf requested changes

2024-01-25 07:03 UTC, theusaf commented on lib/main.dart
> +        initialLocation: skipSetUp ? '/main' : '/main', routes: routes);
This change breaks the tests. Once everything else is validated, we should revert this.

2024-01-26 23:20 UTC, bpugh5 approved these changes
Watched this happen in real time. Great job! Other than that hard-coded route Daniel mentioned, the rest looks good!

2024-01-26 23:39 UTC, stalberm submitted a review, later dismissed

2024-01-26 23:52 UTC, theusaf approved these changes

2024-01-26 23:52 UTC, stalberm approved these changes

2024-01-26 23:52 UTC, merged